//load shared library for slack notification
//@Library('shared-library')_

import groovy.json.JsonOutput

def sendSlackMessage() {
  jenkins_image = ":jenkins:"
  beer_image = ":beer:"
  long epoch = System.currentTimeMillis()/1000
  def BUILD_COLORS = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']
  
  def slack = JsonOutput.toJson(
      [
            icon_emoji: jenkins_image,
            attachments: [[
              title: "Jenkins Job Alert - ${currentBuild.currentResult}",
              text:  "Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}  ${beer_image}\n Details at: ${env.BUILD_URL}console",
              fallback: "ICDC Jenkins Build",
              color: "${BUILD_COLORS[currentBuild.currentResult]}",
              footer: "icdc devops",
              ts: epoch,
              mrkdwn_in: ["footer", "title"],
           ]]
        ]
    )
    try {
        sh "curl -X POST -H 'Content-type: application/json' --data '${slack}'  '${SLACK_URL}'"
    } catch (err) {
        echo "${err} Slack notify failed"
    }
}

pipeline {

  agent {
    node {
      label 'slave-ncias-d2320-c'
    }
  }
  parameters {
    //listGitBranches(branchFilter: '.*', credentialsId: '', defaultValue: 'master', name: 'Tag', quickFilterEnabled: false, remoteURL: 'https://github.com/CBIIT/icdc-codebase', selectedValue: 'DEFAULT', sortMode: 'NONE', tagFilter: '.*', type: 'PT_BRANCH_TAG')
    // gitParameter(branchFilter: '.*', credentialsId: '', defaultValue: 'master', name: 'Tag', quickFilterEnabled: false, remoteURL: 'https://github.com/CBIIT/icdc-codebase', selectedValue: 'DEFAULT', sortMode: 'NONE', tagFilter: '.*', type: 'PT_BRANCH_TAG')
    gitParameter(branchFilter: 'origin/(.*)', 
            defaultValue: 'Develop', 
            name: 'Tag', 
            type: 'PT_BRANCH_TAG',
            quickFilterEnabled: false, 
            selectedValue: 'DEFAULT', 
            sortMode: 'NONE', 
            tagFilter: '*', 
            useRepository: 'https://github.com/CBIIT/icdc-codebase')
    extendedChoice( 
            name: 'Environment', 
            defaultValue: 'demo', 
            description: 'Choose the environment to build', 
            type: 'PT_SINGLE_SELECT',
            value: 'ecs-dev' )
  }
   // triggers { 
   //   pollSCM('H/15 * * * 1-5') 
   //  }
  options {
    timestamps()
  }
  tools { 
    maven 'Default' 
    jdk 'Default' 
  }
  stages {
    stage('checkout'){
      steps {
        checkout([$class: 'GitSCM', 
          branches: [[name: "${params.Tag}"]], 
          doGenerateSubmoduleConfigurations: 
          false, extensions: [], submoduleCfg: [], 
          userRemoteConfigs: 
          [[url: 'https://github.com/CBIIT/icdc-codebase']]])

        dir('icdc-devops'){
          git branch: 'master',
            url: 'https://github.com/CBIIT/icdc-devops.git'
        }
      }
    }
    stage('Set Environment'){
      environment {
        SLACK_URL = "${SLACK_ECS_ICDC_URL}"
      }
        steps {
          script {
            switch("${params.Environment}") {
              case "demo":
                withCredentials([string(credentialsId: 'ecs_dev_bearer', variable: 'BEARER')]) {
                  env.NEO4J_IP    = "${NEO4J_DEMO_IP}"
                  env.BEARER = "${BEARER}"
                  env.TIER  = "ecc-dev"
                  
                }
              break
              default:
                withCredentials([string(credentialsId: 'ecs_dev_bearer', variable: 'BEARER')]) {
                  env.NEO4J_IP    = "${NEO4J_DEMO_IP}"
                  env.BEARER = "${BEARER}"
                  env.TIER  = "ecs-dev"
                }
              break
            }
          }
        }
    }
    stage('Build') {
      environment {
        VERSION = "${params.Tag}"
        ECS_DEV_URL = "caninecommons-ecs-dev.nci.nih.gov"
      }
      steps {
      wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
        withCredentials([string(credentialsId: 'ecs_dev_bearer', variable: 'BEARER'), 
                usernamePassword(credentialsId: 'neo4j_ecs_dev_user', passwordVariable: 'NEO4J_PASSWORD', usernameVariable: 'NEO4J_USER'),
                usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER'),
                string(credentialsId: 'fence-id', variable: 'FENCE_ID'),
                string(credentialsId: 'ecr_repo', variable: 'ECR'),
                string(credentialsId: 'fence-credential', variable: 'FENCE_CREDENTIAL')]) {

          ansiblePlaybook( 
                  playbook: '${WORKSPACE}/icdc-devops/ansible/build-cloudone-ecs.yml', 
                  inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
                  colorized: true) 
        }
      }
    }
    }
    stage('deploy'){
      steps{
        wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
          ansiblePlaybook( 
                playbook: '${WORKSPACE}/icdc-devops/ansible/deploy-cloudone-ecs.yml', 
                inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
                colorized: true)
        }
      }
    }
  }
  post {
    always {
      
      sendSlackMessage()
    }
  }
}
