
import groovy.json.JsonOutput

def sendSlackMessage() {
  jenkins_image = ":jenkins:"
  beer_image = ":beer:"
  long epoch = System.currentTimeMillis()/1000
  def BUILD_COLORS = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']
  
  def slack = JsonOutput.toJson(
      [
            icon_emoji: jenkins_image,
            attachments: [[
              title: "Jenkins Job Alert - ${currentBuild.currentResult}",
              text:  "Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}  ${beer_image}\n Details at: ${env.BUILD_URL}console",
              fallback: "Bento Jenkins Build",
              color: "${BUILD_COLORS[currentBuild.currentResult]}",
              footer: "bento devops",
              ts: epoch,
              mrkdwn_in: ["footer", "title"],
           ]]
        ]
    )
    try {
        sh "curl -X POST -H 'Content-type: application/json' --data '${slack}'  '${SLACK_URL}'"
    } catch (err) {
        echo "${err} Slack notify failed"
    }
}


pipeline {
  agent {
    node {
      label 'cicd_microservice'
    }
  }
  parameters {
    extendedChoice( 
        name: 'Region', 
        defaultValue: 'us-east-1', 
        description: 'Choose aws region to build', 
        type: 'PT_SINGLE_SELECT',
        value: 'us-east-1' )
    gitParameter(branchFilter: 'origin/(.*)', 
       defaultValue: 'main', 
       name: 'OpenPedCan_Tag', 
       type: 'PT_BRANCH_TAG',
       quickFilterEnabled: false, 
       selectedValue: 'DEFAULT', 
       sortMode: 'ASCENDING_SMART', 
       tagFilter: '*', 
       useRepository: 'https://github.com/PediatricOpenTargets/OpenPedCan-api.git')
    string(
      defaultValue: 'rserver',
      description: 'Project Name',
      name: 'ProjectName')

  }
  options {
    ansiColor('xterm')
  }
  tools {
    maven 'Default' 
    jdk 'Default' 
  }
  stages{
    stage('checkout'){
      steps {

        checkout([$class: 'GitSCM', 
          branches: [[name: "${params.OpenPedCan_Tag}"]], 
          doGenerateSubmoduleConfigurations: 
          false, extensions: [], submoduleCfg: [], 
          userRemoteConfigs: 
          [[url: 'https://github.com/PediatricOpenTargets/OpenPedCan-api.git']]])

        checkout( poll: false, 
        changelog:false,
        scm: [$class: 'GitSCM', 
        branches: [[name: '*/master']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [[$class: 'DisableRemotePoll'],
        [$class: 'PathRestriction', excludedRegions: '*'], 
        [$class: 'RelativeTargetDirectory', 
        relativeTargetDir: 'icdc-devops']], 
        submoduleCfg: [], 
        userRemoteConfigs: 
        [[url: 'https://github.com/CBIIT/icdc-devops.git']]])

        }
 
    }
    // stage('Set Environment'){
    //   environment {
    //     SLACK_URL = "${SLACK_URL}"
    //     VERSION = "${params.Frontend_Tag}"
    //   }
    //     steps {
    //       script {
    //         switch("${params.Environment}") {
    //           case "dev":
    //             withCredentials([usernamePassword(credentialsId: 'ins_dev_neo4j_user', passwordVariable: 'NEO4J_PASS', usernameVariable: 'NEO4J_USER'),
    //             string(credentialsId: 'ins_dev_bearer', variable: 'BEARER')]) {
    //               env.TIER  = "dev"
    //               env.NEO4J_USER = "${NEO4J_USER}"
    //               env.NEO4J_PASS  = "${NEO4J_PASS}"
    //               env.BEARER = "${BEARER}"

    //             }
    //     break
    //           default:
    //             withCredentials([usernamePassword(credentialsId: 'ins_dev_neo4j_user', passwordVariable: 'NEO4J_PASS', usernameVariable: 'NEO4J_USER')]) {
    //               env.TIER  = "dev"
    //               env.NEO4J_USER = "${NEO4J_USER}"
    //               env.NEO4J_PASS  = "${NEO4J_PASS}"
    //               env.BEARER = "${BEARER}"

    //             }
    //           break
    //         }
    //       }
    //     }
    // }

    stage('build'){
      environment {
       VERSION = "${params.OpenPedCan_Tag}"
      }
    steps {

      wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
        withCredentials([usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER')]){
                  ansiblePlaybook(        
                    playbook: '${WORKSPACE}/icdc-devops/ansible/rserver-build.yml', 
                  inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
            extraVars: [
            project: 'rserver',

                        ],
            colorized: true)
        }
      }
    }
    }

    stage('deploy'){
    environment {
       VERSION = "${params.OpenPedCan_Tag}"
      }
      steps{
        node('cicd_microservice') {
        checkout( changelog:false,
        poll: false,
        scm: [$class: 'GitSCM', 
        branches: [[name: '*/master']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [[$class: 'DisableRemotePoll'],
        [$class: 'PathRestriction', excludedRegions: '*'], 
        [$class: 'RelativeTargetDirectory', 
        relativeTargetDir: 'icdc-devops']], 
        submoduleCfg: [], 
        userRemoteConfigs: 
        [[url: 'https://github.com/CBIIT/icdc-devops.git']]
        ])
      
      wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
          ansiblePlaybook( 
                playbook: '${WORKSPACE}/icdc-devops/ansible/rserver-deploy.yml', 
                inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
                extraVars: [
          project: 'rserver'
                    ],
          colorized: true)
        }
      }
      }
    }



  }
  post {

  always {

      sendSlackMessage()

    }


  cleanup {
  
    cleanWs()
    
  }

  }
}