
import groovy.json.JsonOutput

def sendSlackMessage() {
  jenkins_image = ":jenkins:"
  beer_image = ":beer:"
  long epoch = System.currentTimeMillis()/1000
  def BUILD_COLORS = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']
  
  def slack = JsonOutput.toJson(
      [
            icon_emoji: jenkins_image,
            attachments: [[
              title: "Jenkins Job Alert - ${currentBuild.currentResult}",
              text:  "Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}  ${beer_image}\n Details at: ${env.BUILD_URL}console",
              fallback: "Bento Jenkins Build",
              color: "${BUILD_COLORS[currentBuild.currentResult]}",
              footer: "bento devops",
              ts: epoch,
              mrkdwn_in: ["footer", "title"],
           ]]
        ]
    )
    try {
        sh "curl -X POST -H 'Content-type: application/json' --data '${slack}'  '${SLACK_URL}'"
    } catch (err) {
        echo "${err} Slack notify failed"
    }
}


pipeline { 
	agent {
		node {
			label 'commons-docker-ncias-p2236-v'
		}
	}
	parameters {
    extendedChoice( 
        name: 'Environment', 
        defaultValue: 'dev', 
        description: 'Choose the environment to build', 
        type: 'PT_SINGLE_SELECT',
        value: 'dev,qa,stage,prod' )
   	gitParameter(branchFilter: 'origin/(.*)', 
       defaultValue: 'main', 
       name: 'Dictionary_Tag', 
       type: 'PT_BRANCH_TAG',
       quickFilterEnabled: false, 
       selectedValue: 'DEFAULT', 
       sortMode: 'ASCENDING_SMART', 
       tagFilter: '*', 
       useRepository: 'https://github.com/wfy1997/bentoWindMillReengineer.git')
       
       //https://github.com/CBIIT/visualiser-standalone

  }

  options {
  	ansiColor('xterm')
  }
  tools {
  	maven 'Default' 
    jdk 'Default' 
  }
  stages{
  	stage('checkout'){
  		steps {
			checkout([$class: 'GitSCM',
				branches: [[name: "${params.Dictionary_Tag}"]],
				doGenerateSubmoduleConfigurations: false,
				extensions: [[$class: 'RelativeTargetDirectory',
				relativeTargetDir: 'visualiser-standalone']],
				submoduleCfg: [],
				userRemoteConfigs: 
				[[url: 'https://github.com/wfy1997/bentoWindMillReengineer.git']]])

  			checkout( poll: false, 
				changelog:false,
				scm: [$class: 'GitSCM', 
				branches: [[name: '*/master']], 
				doGenerateSubmoduleConfigurations: false, 
				extensions: [[$class: 'DisableRemotePoll'],
				[$class: 'PathRestriction', excludedRegions: '*'], 
				[$class: 'RelativeTargetDirectory', 
				relativeTargetDir: 'icdc-devops']], 
				submoduleCfg: [], 
				userRemoteConfigs: 
				[[url: 'https://github.com/CBIIT/icdc-devops.git']]])

        }
 
  	}
    
  	stage('build'){
      environment {
        DICTIONARY_VERSION = "${params.Dictionary_Tag}-${BUILD_NUMBER}"
        TIER = "${params.Environment}"
      }
 		steps {
 			wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
 				withCredentials([
          usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER'),
          file(credentialsId: 'ansible_host_file', variable: 'host_file'),
          string(credentialsId: 'docker_host', variable: 'DOCKER_HOST'),
          string(credentialsId: 'tls_hostname', variable: 'TLS_HOSTNAME')])
        {
          sh "cp ${host_file} ${WORKSPACE}/icdc-devops/ansible/hosts"
          ansiblePlaybook(  			
              playbook: '${WORKSPACE}/icdc-devops/ansible/build-icdc-data-dictionary.yml', 
            	inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
						  extraVars: [
                       		tier: "${params.Environment}",
                        ],
						colorized: true)
 				}
 			}
 		}
  	}

  	stage('deploy'){
	  environment {
       DICTIONARY_VERSION = "${params.Dictionary_Tag}-${BUILD_NUMBER}"
       SLACK_URL = "${ICDC_SLACK_URL}"
      }
  		steps{
			wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
				withCredentials([
          string(credentialsId: 'newrelic_license_key', variable: 'NEWRELIC_LIC_KEY'),
          usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER')
          ])
        {

  				ansiblePlaybook( 
            		playbook: '${WORKSPACE}/icdc-devops/ansible/deploy-icdc-data-dictionary.yml', 
            		inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
            		extraVars: [
                      tier: "${params.Environment}"
                    ],
					colorized: true)
  			}
		   }
  		}
  	}
  }
  post {

	always {

      sendSlackMessage()

    }

	success {

		script {
			withCredentials([string(credentialsId: 'git_credential_token', variable: 'git_token')]) {
				sh label: 'GIT-Tag Dictionary', script: '''#!/bin/bash
				cd ${WORKSPACE}/visualiser-standalone
				gitURL=$(git config remote.origin.url | sed 's|^.*//||')
				echo "Applying tag $Dictionary_Tag to URL:  $gitURL"
				git config user.email "jenkins@bento-tools.org"
				git config user.name "Bento Jenkins"
				git tag --no-sign -a ${Dictionary_Tag}-icdc-${BUILD_NUMBER} -m "Jenkins tag: ${Dictionary_Tag}-${BUILD_NUMBER}"
				git push https://${git_token}:x-oauth-basic@${gitURL} --tags
				
				'''
			
				}
			}
		
		}

	cleanup {
	
	  cleanWs()
    
	}

  }
}