pipeline {
	agent {
		node {
			label 'cicd_microservice'
		}
	}
	parameters {
    gitParameter(branchFilter: 'origin/(.*)', 
        defaultValue: 'master', 
        name: 'Tag', 
        type: 'PT_BRANCH_TAG',
        quickFilterEnabled: false, 
        selectedValue: 'DEFAULT', 
        sortMode: 'ASCENDING_SMART', 
        tagFilter: '*', 
        useRepository: 'https://github.com/CBIIT/microservices')
    extendedChoice( 
        name: 'Environment', 
        defaultValue: 'test', 
        description: 'Choose the environment to build', 
        type: 'PT_SINGLE_SELECT',
        value: 'sandbox,dev,test,qa,stage,prod' )
  }
  options {
  	ansiColor('xterm')
  }
  tools {
  	maven 'Default' 
    jdk 'Default' 
  }
  stages{
  	stage('checkout'){
  		steps {
  			checkout([$class: 'GitSCM', 
  				branches: [[name: "${params.Tag}"]], 
  				doGenerateSubmoduleConfigurations: 
  				false, extensions: [], submoduleCfg: [], 
  				userRemoteConfigs: 
  				[[url: 'https://github.com/CBIIT/microservices']]])

  			dir('icdc-devops'){
  				git branch: 'master',
    				url: 'https://github.com/CBIIT/icdc-devops.git'
  			}
  		}
 
  	}
    stage('Set Environment'){
        environment {
          SANDBOX_URL = "k9dc.essential-dev.com"
          TEST_URL = "bento.essential-dev.com"
          DEV_URL = "caninecommons-dev.cancer.gov"
          QA_URL = "caninecommons-qa.cancer.gov"
          STAGE_URL = "caninecommons-stage.cancer.gov"
          PROD_URL = "caninecommons.cancer.gov" 
          VERSION = "${params.Tag}"
        }
        steps {
          script {
            switch("${params.Environment}") {
              case "sandbox":
                withCredentials([file(credentialsId: 'sandbox_env_file', variable: 'secret_file')]) {
                sh "cp ${secret_file} ${WORKSPACE}/src/main/frontend/.env"
                sh "cd ${WORKSPACE}/src/main/frontend/ && sed -i 's,tag_version,${VERSION},g' .env"
                sh "cat ${WORKSPACE}/src/main/frontend/.env"
      
                }
              break
              case "test":
                withCredentials([file(credentialsId: 'test_env_file', variable: 'secret_file')]) {
                  sh "cp ${secret_file} ${WORKSPACE}/src/main/frontend/.env"
                  sh "cd ${WORKSPACE}/src/main/frontend/ && sed -i 's,tag_version,${VERSION},g' .env"
                  env.TOMCAT01_IP = "${TOMCAT01_IP}"
                  env.TOMCAT02_IP = "${TOMCAT02_IP}"
                  env.NEO4J_IP    = "${NEO4J_IP}"
                  env.FENCE_URL   = "bento.essential-dev.com"
                }
              break
              default:
                println "Select valid option"
              break
              }
          }
        }
    }
  	stage('build'){
 		environment {
 			SLACK_URL = "${SLACK_URL}"
 		}
 		steps {
 			wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
 				withCredentials([string(credentialsId: 'authorization_bearer', variable: 'BEARER'), 
          			usernamePassword(credentialsId: 'neo4j_user', passwordVariable: 'NEO4J_PASSWORD', usernameVariable: 'NEO4J_USER'),
          			string(credentialsId: 'fence-id', variable: 'FENCE_ID'),
          			usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER'),
          			string(credentialsId: 'fence-credential', variable: 'FENCE_CREDENTIAL')]) {

 					ansiblePlaybook( 
            			playbook: '${WORKSPACE}/icdc-devops/ansible/build.yml', 
            			inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
            			colorized: true) 
 				}
 			}
 		}
  	}
    stage('deploy-frontend'){
      steps{
        wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
          ansiblePlaybook( 
                playbook: '${WORKSPACE}/icdc-devops/ansible/deploy-frontend.yml', 
                inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
                colorized: true)
        }
      }
    }
  	stage('deploy'){
  		steps{
  			wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
  				ansiblePlaybook( 
            		playbook: '${WORKSPACE}/icdc-devops/ansible/deploy-backend.yml', 
            		inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
            		colorized: true)
  			}
  		}
  	}
  }
}