pipeline {
	agent {
		node {
			label 'cicd_microservice'
		}
	}
	parameters {
    gitParameter(branchFilter: 'origin/(.*)', 
        defaultValue: 'master', 
        name: 'Tag', 
        type: 'PT_BRANCH_TAG',
        quickFilterEnabled: false, 
        selectedValue: 'DEFAULT', 
        sortMode: 'ASCENDING_SMART', 
        tagFilter: '*', 
        useRepository: 'https://github.com/CBIIT/microservices')
    extendedChoice( 
        name: 'Environment', 
        defaultValue: 'sandbox', 
        description: 'Choose the environment to build', 
        type: 'PT_SINGLE_SELECT',
        value: 'sandbox,dev,qa,stage,prod' )
  }
  options {
  	ansiColor('xterm')
  }
  tools {
  	maven 'Default' 
    jdk 'Default' 
  }
  stages{
  	stage('checkout'){
  		steps {
  			checkout([$class: 'GitSCM', 
  				branches: [[name: "${params.Tag}"]], 
  				doGenerateSubmoduleConfigurations: 
  				false, extensions: [], submoduleCfg: [], 
  				userRemoteConfigs: 
  				[[url: 'https://github.com/CBIIT/microservices']]])

  			dir('icdc-devops'){
  				git branch: 'master',
    				url: 'https://github.com/CBIIT/icdc-devops.git'
  			}
  		}
 
  	}
  	stage('build'){
  		wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
 			environment {
 				SLACK_URL = "${SLACK_URL}"
 			}
 			steps {
 				withCredentials([string(credentialsId: 'authorization_bearer', variable: 'BEARER'), 
          			usernamePassword(credentialsId: 'neo4j_user', passwordVariable: 'NEO4J_PASSWORD', usernameVariable: 'NEO4J_USER'),
          			string(credentialsId: 'fence-id', variable: 'FENCE_ID'),
          			usernamePassword(credentialsId: 'docker-login', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER'),
          			string(credentialsId: 'fence-credential', variable: 'FENCE_CREDENTIAL')]) {

 					ansiblePlaybook( 
            			playbook: '${WORKSPACE}/icdc-devops/ansible/cicd.yml', 
            			inventory: '${WORKSPACE}/icdc-devops/ansible/hosts', 
            			colorized: true) 
 				}
 			}
 		}
  	}
  }
}