resource "secret_resource" "devops_ssh_key_public" {}
resource "secret_resource" "devops_ssh_key_private" {}
resource "secret_resource" "devops_user" {}
resource "secret_resource" "admin_user" {}
resource "secret_resource" "admin_password" {}
resource "secret_resource" "icdcTomcat_password" {}
resource "secret_resource" "new_relic_license_key" {}
resource "secret_resource" "neo4j_password" {}
resource "secret_resource" "sumologic_accessid" {}
resource "secret_resource" "sumologic_accesskey" {}